FROM quay.io/dmaa/higgs-audio-vllm:latest AS base

WORKDIR /opt/ml/code

# Copy the workspace from the base image itself
COPY /vllm-workspace/ /opt/ml/code/

EXPOSE 8080

ENTRYPOINT ["python3", "-m", "vllm.entrypoints.bosonai.api_server"]
