name: Release Package

on:
  push:
    tags:
      - 'emd-*'  # Triggers on tags starting with 'emd-'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify your Python version

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3

    - name: Build wheel
      run: poetry build -f wheel

    - name: Get tag name
      id: get_tag
      run: echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Rename wheel
      run: |
        WHEEL_FILE=$(ls dist/*.whl)
        mv "$WHEEL_FILE" "dist/${{ env.TAG_NAME }}.whl"

    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Release ${{ env.TAG_NAME }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/${{ env.TAG_NAME }}.whl
        asset_name: ${{ env.TAG_NAME }}.whl
        asset_content_type: application/zip
